repos:
-   repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: ['--config=setup.cfg']

exclude: "
  ^$\
  |versioneer\\.py\
  |veros/_version.py\
  |doc\
  "
